name: "Code checks"

on:
  push:
    branches:
      - "**"
  pull_request: ~

jobs:
  test-zig:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        zig-version:
          - "0.15.1"
          - "0.15.2"
          - "latest"
    runs-on: "${{ matrix.os }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2

      - name: "Install Zig"
        uses: "mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29" # v2.2.1
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ matrix.zig-version }}"

      - name: "Build"
        run: "zig build"

      - name: "Lint"
        run: "zig fmt --check ."

  test-goreleaser:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2

      - name: "Generate GoReleaser config"
        uses: "docker://ghcr.io/djmattyg007/jsonnet:0.21.0@sha256:890ebf3d1838ad8de9aac3c9f9c7152971bf3a6258e748e169b8d2d0423a48e4"
        with:
          args: "jsonnet --output-file .goreleaser.yaml dev/goreleaser.jsonnet"

      - name: "GoReleaser check"
        uses: "goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29" # v7.0.0
        with:
          args: "check --verbose"

      - name: "Install Zig"
        uses: "mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29" # v2.2.1
        with:
          version: "0.15.2"
          cache-key: "0.15.2"

      - name: "GoReleaser test build"
        uses: "goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29" # v7.0.0
        with:
          args: "build --verbose --snapshot"
