name: "Config checks"

on:
  push:
    branches:
      - "**"
  pull_request: ~

jobs:
  test-config:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6.0.1

      - name: "Lint config"
        uses: "docker://ghcr.io/djmattyg007/jsonnet:0.21.0@sha256:8f6a6f6826be584c73106d9140d6cb779459ffc79679162c111dcda14622040e"
        with:
          args: "jsonnet-lint dev/goreleaser.jsonnet"

      - name: "Check config formatting"
        uses: "docker://ghcr.io/djmattyg007/jsonnet:0.21.0@sha256:8f6a6f6826be584c73106d9140d6cb779459ffc79679162c111dcda14622040e"
        with:
          args: "jsonnetfmt --string-style d --test dev/goreleaser.jsonnet"

      - name: "Run actionlint"
        uses: "reviewdog/action-actionlint@83e4ed25b168066ad8f62f5afbb29ebd8641d982" # v1.69.1
        with:
          fail_level: "warning"

      - name: "Run gitleaks"
        uses: "reviewdog/action-gitleaks@2b7b5685e3e3eecddab5d30cfa04f18123031421" # v1.8.0
        with:
          fail_level: "warning"
