name: "CI"

on:
  push: ~
  pull_request: ~

jobs:
  test-zig:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        zig-version:
          - "0.15.1"
          - "0.15.2"
          - "latest"
    runs-on: "${{ matrix.os }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0

      - name: "Install Zig"
        uses: "mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f" # v2.0.5
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ matrix.zig-version }}"

      - name: "Build"
        run: "zig build"

      - name: "Lint"
        run: "zig fmt --check ."

  test-goreleaser:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3" # v6.0.0

      - name: "Lint config"
        uses: "docker://ghcr.io/djmattyg007/jsonnet:0.21.0@sha256:4c38928922c5d532bfbc0fe9de1b06a013988f4495f35604a30ed4e96b5c51e5"
        with:
          args: "jsonnet-lint goreleaser.jsonnet"

      - name: "Check config formatting"
        uses: "docker://ghcr.io/djmattyg007/jsonnet:0.21.0@sha256:4c38928922c5d532bfbc0fe9de1b06a013988f4495f35604a30ed4e96b5c51e5"
        with:
          args: "jsonnetfmt --string-style d --test goreleaser.jsonnet"

      - name: "Generate Goreleaser config"
        uses: "docker://ghcr.io/djmattyg007/jsonnet:0.21.0@sha256:4c38928922c5d532bfbc0fe9de1b06a013988f4495f35604a30ed4e96b5c51e5"
        with:
          args: "jsonnet --output-file .goreleaser.yaml goreleaser.jsonnet"

      - name: "Goreleaser check"
        uses: "goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a" # v6.4.0
        with:
          args: "check"

      - name: "Goreleaser build"
        uses: "goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a" # v6.4.0
        with:
          args: "build"
