name: "Release"

on:
  push:
    tags:
      - "v1*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6.0.1
        with:
          fetch-depth: 0

      - name: "Install Zig"
        uses: "mlugg/setup-zig@e7d1537c378b83b8049f65dda471d87a2f7b2df2" # v2.2.0
        with:
          version: "0.15.2"
          cache-key: "0.15.2"

      # - name: "Install Syft"
      #   id: "install-syft"
      #   uses: "anchore/sbom-action/download-syft@fbfd9c6c189226748411491745178e0c2017392d" # v0.20.10

      - name: "Import GPG key"
        id: "import-gpg"
        uses: "crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec" # v6.3.0
        with:
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
          passphrase: "${{ secrets.GPG_PASSPHRASE }}"

      - name: "Generate GoReleaser config"
        uses: "docker://ghcr.io/djmattyg007/jsonnet:0.21.0@sha256:011e4286c47cbac9193a16d5986ddd65279e538742c4830b0baf2cf072f0fb41"
        with:
          args: 'jsonnet --output-file .goreleaser.yaml dev/goreleaser.jsonnet'

      - name: "Generate release notes"
        run: |
          perl -s -0777 -p -e 's/.*(## $tag - .*?)(## .*|$)/$1/s' -- -tag="${{ github.ref_name }}" CHANGELOG.md | tail -n+3 | tee release-notes.md

      - name: "Run GoReleaser"
        uses: "goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a" # v6.4.0
        with:
          args: "release --verbose --clean --release-notes=release-notes.md"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GPG_FINGERPRINT: "${{ steps.import-gpg.outputs.fingerprint }}"
          AUR_SSH_PRIVATE_KEY: "${{ secrets.AUR_SSH_PRIVATE_KEY }}"
